### ISSUE TITLE
Alternate use from ros_control Jointeffortcontroller

### ISSUE THREAD

**Issue by offjangir** [modulabs/gdyn-arm-tutorial#2]
I have been trying to find an interface to jointeffortcontroller which directly publishes the torque commands to the joint.  Can this controller be used for that? is it more stable then that?

**Comment by elton-choi** [comment]
@offjangir  Yes, these controllers benchmarked joint group position controller in ros controllers. joint group position controller uses joint effort interface and it can handle all joints together so that you can use kinematics or  compensate dynamics.
